# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True)),
                ('genero', models.CharField(choices=[('RC', 'Rock'), ('PP', 'Pop'), ('CL', 'Club'), ('RG', 'Reggaetón'), ('BD', 'Banda'), ('EL', 'Electrónica'), ('OT', 'Otro')], max_length=20)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authors.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True)),
                ('genero', models.CharField(choices=[('RC', 'Rock'), ('PP', 'Pop'), ('CL', 'Club'), ('RG', 'Reggaetón'), ('BD', 'Banda'), ('EL', 'Electrónica'), ('OT', 'Otro')], max_length=20)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
            ],
        ),
    ]
